package ordenacoes;

import javax.swing.JOptionPane;
import java.util.*;
import java.util.stream.Collectors;

/**
 *
 * @author apweb
 */
public class JanelaMetodos extends javax.swing.JFrame {

    private final GerenciadorArquivo gerenciadorArquivo;
    private final Map<String, javax.swing.JCheckBox> caixasSelecao;

    /**
     * Creates new form JanelaMetodos
     * @param gerenciadorArquivo
     */
    public JanelaMetodos(GerenciadorArquivo gerenciadorArquivo) {
        this.gerenciadorArquivo = gerenciadorArquivo;
        this.caixasSelecao = new HashMap<>();
        initComponents();
        inicializarCaixasSelecao();
        setLocationRelativeTo(null);
    }

    private void inicializarCaixasSelecao() {
        caixasSelecao.put("selecao", checkSelecao);
        caixasSelecao.put("bolha", checkBolha);
        caixasSelecao.put("insercao", checkInsercao);
        caixasSelecao.put("shell", checkShell);
        caixasSelecao.put("pente", checkPente);
        caixasSelecao.put("agitacao", checkAgitacao);
        caixasSelecao.put("quick", checkQuick);
    }

    private void verificarLimiteSelecao() {
        long quantidadeSelecionada = caixasSelecao.values().stream()
                .filter(javax.swing.JCheckBox::isSelected)
                .count();

        if (quantidadeSelecionada >= 2) {
            caixasSelecao.values().forEach(cb -> {
                if (!cb.isSelected()) {
                    cb.setEnabled(false);
                }
            });
        } else {
            caixasSelecao.values().forEach(cb -> cb.setEnabled(true));
        }
    }

    private void limparResultados() {
        lblMetodo1.setText("Método 1");
        txtTempo1.setText("");
        txtComparacoes1.setText("");
        txtTrocas1.setText("");

        lblMetodo2.setText("Método 2");
        txtTempo2.setText("");
        txtComparacoes2.setText("");
        txtTrocas2.setText("");
    }

    private void executarOrdenacao() {
        List<String> metodosSelecionados = caixasSelecao.entrySet().stream()
                .filter(entrada -> entrada.getValue().isSelected())
                .map(Map.Entry::getKey)
                .collect(Collectors.toList());

        if (metodosSelecionados.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Selecione pelo menos um método!",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        limparResultados();

        List<Integer> numerosOriginais = gerenciadorArquivo.getNumeros();
        AlgoritmosOrdenacao algoritmos = new AlgoritmosOrdenacao();

        if (metodosSelecionados.size() > 0) {
            String metodo1 = metodosSelecionados.get(0);
            List<Integer> numerosParaOrdenar1 = new ArrayList<>(numerosOriginais);
            long tempoInicio1 = System.currentTimeMillis();
            ResultadoOrdenacao resultado1 = algoritmos.ordenar(metodo1, numerosParaOrdenar1);
            long tempoFim1 = System.currentTimeMillis();

            lblMetodo1.setText(metodo1);
            txtTempo1.setText(String.valueOf(tempoFim1 - tempoInicio1));
            txtComparacoes1.setText(String.valueOf(resultado1.getComparacoes()));
            txtTrocas1.setText(String.valueOf(resultado1.getTrocas()));
        }
        
        if (metodosSelecionados.size() > 1) {
            String metodo2 = metodosSelecionados.get(1);
            List<Integer> numerosParaOrdenar2 = new ArrayList<>(numerosOriginais);
            long tempoInicio2 = System.currentTimeMillis();
            ResultadoOrdenacao resultado2 = algoritmos.ordenar(metodo2, numerosParaOrdenar2);
            long tempoFim2 = System.currentTimeMillis();

            lblMetodo2.setText(metodo2);
            txtTempo2.setText(String.valueOf(tempoFim2 - tempoInicio2));
            txtComparacoes2.setText(String.valueOf(resultado2.getComparacoes()));
            txtTrocas2.setText(String.valueOf(resultado2.getTrocas()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        painelMetodos = new javax.swing.JPanel();
        checkSelecao = new javax.swing.JCheckBox();
        checkBolha = new javax.swing.JCheckBox();
        checkInsercao = new javax.swing.JCheckBox();
        checkShell = new javax.swing.JCheckBox();
        checkPente = new javax.swing.JCheckBox();
        checkAgitacao = new javax.swing.JCheckBox();
        checkQuick = new javax.swing.JCheckBox();
        javax.swing.JButton botaoOrdenar = new javax.swing.JButton();
        painelResultados = new javax.swing.JPanel();
        lblMetodo1 = new javax.swing.JLabel();
        lblTempo1 = new javax.swing.JLabel();
        txtTempo1 = new javax.swing.JTextField();
        lblComparacoes1 = new javax.swing.JLabel();
        txtComparacoes1 = new javax.swing.JTextField();
        lblTrocas1 = new javax.swing.JLabel();
        txtTrocas1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblMetodo2 = new javax.swing.JLabel();
        lblTempo2 = new javax.swing.JLabel();
        txtTempo2 = new javax.swing.JTextField();
        lblComparacoes2 = new javax.swing.JLabel();
        txtComparacoes2 = new javax.swing.JTextField();
        lblTrocas2 = new javax.swing.JLabel();
        txtTrocas2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Seleção de Métodos de Ordenação");

        painelMetodos.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione os métodos (máximo 2):"));

        checkSelecao.setText("selecao");
        checkSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSelecaoActionPerformed(evt);
            }
        });

        checkBolha.setText("bolha");
        checkBolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBolhaActionPerformed(evt);
            }
        });

        checkInsercao.setText("insercao");
        checkInsercao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInsercaoActionPerformed(evt);
            }
        });

        checkShell.setText("shell");
        checkShell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkShellActionPerformed(evt);
            }
        });

        checkPente.setText("pente");
        checkPente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPenteActionPerformed(evt);
            }
        });

        checkAgitacao.setText("agitacao");
        checkAgitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAgitacaoActionPerformed(evt);
            }
        });

        checkQuick.setText("quick");
        checkQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkQuickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelMetodosLayout = new javax.swing.GroupLayout(painelMetodos);
        painelMetodos.setLayout(painelMetodosLayout);
        painelMetodosLayout.setHorizontalGroup(
            painelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMetodosLayout.createSequentialGroup()
                        .addComponent(checkSelecao)
                        .addGap(18, 18, 18)
                        .addComponent(checkBolha)
                        .addGap(18, 18, 18)
                        .addComponent(checkInsercao))
                    .addGroup(painelMetodosLayout.createSequentialGroup()
                        .addComponent(checkShell)
                        .addGap(18, 18, 18)
                        .addComponent(checkPente)
                        .addGap(18, 18, 18)
                        .addComponent(checkAgitacao))
                    .addComponent(checkQuick))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelMetodosLayout.setVerticalGroup(
            painelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSelecao)
                    .addComponent(checkBolha)
                    .addComponent(checkInsercao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelMetodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkShell)
                    .addComponent(checkPente)
                    .addComponent(checkAgitacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkQuick)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoOrdenar.setText("Ordenar");
        botaoOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOrdenarActionPerformed(evt);
            }
        });

        painelResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        lblMetodo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMetodo1.setText("Método 1");

        lblTempo1.setText("Tempo (ms):");

        txtTempo1.setEditable(false);

        lblComparacoes1.setText("Comparações:");

        txtComparacoes1.setEditable(false);

        lblTrocas1.setText("Trocas:");

        txtTrocas1.setEditable(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblMetodo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMetodo2.setText("Método 2");

        lblTempo2.setText("Tempo (ms):");

        txtTempo2.setEditable(false);

        lblComparacoes2.setText("Comparações:");

        txtComparacoes2.setEditable(false);

        lblTrocas2.setText("Trocas:");

        txtTrocas2.setEditable(false);

        javax.swing.GroupLayout painelResultadosLayout = new javax.swing.GroupLayout(painelResultados);
        painelResultados.setLayout(painelResultadosLayout);
        painelResultadosLayout.setHorizontalGroup(
            painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetodo1)
                    .addGroup(painelResultadosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComparacoes1)
                            .addComponent(lblTempo1)
                            .addComponent(lblTrocas1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTempo1)
                            .addComponent(txtComparacoes1)
                            .addComponent(txtTrocas1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMetodo2)
                    .addGroup(painelResultadosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComparacoes2)
                            .addComponent(lblTempo2)
                            .addComponent(lblTrocas2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTempo2)
                            .addComponent(txtComparacoes2)
                            .addComponent(txtTrocas2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelResultadosLayout.setVerticalGroup(
            painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(painelResultadosLayout.createSequentialGroup()
                        .addComponent(lblMetodo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTempo2)
                            .addComponent(txtTempo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblComparacoes2)
                            .addComponent(txtComparacoes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTrocas2)
                            .addComponent(txtTrocas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(painelResultadosLayout.createSequentialGroup()
                        .addComponent(lblMetodo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTempo1)
                            .addComponent(txtTempo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblComparacoes1)
                            .addComponent(txtComparacoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTrocas1)
                            .addComponent(txtTrocas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelMetodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(painelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void checkSelecaoActionPerformed(java.awt.event.ActionEvent evt) {
        verificarLimiteSelecao();
    }

    private void checkBolhaActionPerformed(java.awt.event.ActionEvent evt) {
        verificarLimiteSelecao();
    }

    private void checkInsercaoActionPerformed(java.awt.event.ActionEvent evt) {
        verificarLimiteSelecao();
    }

    private void checkShellActionPerformed(java.awt.event.ActionEvent evt) {
        verificarLimiteSelecao();
    }

    private void checkPenteActionPerformed(java.awt.event.ActionEvent evt) {
        verificarLimiteSelecao();
    }

    private void checkAgitacaoActionPerformed(java.awt.event.ActionEvent evt) {
        verificarLimiteSelecao();
    }

    private void checkQuickActionPerformed(java.awt.event.ActionEvent evt) {
        verificarLimiteSelecao();
    }

    private void botaoOrdenarActionPerformed(java.awt.event.ActionEvent evt) {
        executarOrdenacao();
    }

    // Variables declaration - do not modify
    private javax.swing.JCheckBox checkAgitacao;
    private javax.swing.JCheckBox checkBolha;
    private javax.swing.JCheckBox checkInsercao;
    private javax.swing.JCheckBox checkPente;
    private javax.swing.JCheckBox checkQuick;
    private javax.swing.JCheckBox checkSelecao;
    private javax.swing.JCheckBox checkShell;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblComparacoes1;
    private javax.swing.JLabel lblComparacoes2;
    private javax.swing.JLabel lblMetodo1;
    private javax.swing.JLabel lblMetodo2;
    private javax.swing.JLabel lblTempo1;
    private javax.swing.JLabel lblTempo2;
    private javax.swing.JLabel lblTrocas1;
    private javax.swing.JLabel lblTrocas2;
    private javax.swing.JPanel painelMetodos;
    private javax.swing.JPanel painelResultados;
    private javax.swing.JTextField txtComparacoes1;
    private javax.swing.JTextField txtComparacoes2;
    private javax.swing.JTextField txtTempo1;
    private javax.swing.JTextField txtTempo2;
    private javax.swing.JTextField txtTrocas1;
    private javax.swing.JTextField txtTrocas2;
    // End of variables declaration
}

