/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ordenacoes;

import javax.swing.JOptionPane;

/**
 *
 * @author apweb
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private GerenciadorArquivo gerenciadorArquivo;
    private JanelaMetodos janelaMetodos;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        this.gerenciadorArquivo = new GerenciadorArquivo();
        initComponents();
        setLocationRelativeTo(null); // Centraliza a janela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        rotuloTitulo = new javax.swing.JLabel();
        botaoCarregarArquivo = new javax.swing.JButton();
        botaoMetodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BenchMark Ordenação");
        setResizable(false);

        rotuloTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        rotuloTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotuloTitulo.setText("BenchMark Ordenação");

        botaoCarregarArquivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        botaoCarregarArquivo.setText("Carregar Arquivo");
        botaoCarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCarregarArquivoActionPerformed(evt);
            }
        });

        botaoMetodos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        botaoMetodos.setText("Métodos");
        botaoMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMetodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rotuloTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 50, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(botaoCarregarArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(botaoMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 50, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(rotuloTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(botaoCarregarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void botaoCarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {
        if (gerenciadorArquivo.carregarArquivo()) {
            JOptionPane.showMessageDialog(this,
                    "Arquivo carregado com sucesso!\nNúmeros encontrados: " +
                            gerenciadorArquivo.getNumeros().size(),
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void botaoMetodosActionPerformed(java.awt.event.ActionEvent evt) {
        if (gerenciadorArquivo.getNumeros().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, carregue um arquivo primeiro!",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (janelaMetodos == null) {
            janelaMetodos = new JanelaMetodos(gerenciadorArquivo);
        }
        janelaMetodos.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botaoCarregarArquivo;
    private javax.swing.JButton botaoMetodos;
    private javax.swing.JLabel rotuloTitulo;
    // End of variables declaration
}